name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Setup
        run: curl -sL https://github.com/sugurumorimoto/dotfiles/blob/master/install.sh | sh
