name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Setup
        run: curl -sL https://raw.githubusercontent.com/sugurumorimoto/dotfiles/0631b319c64505b99ba57cf3770771175834ac35/install.sh | bash
