name: Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: curl -sL https://raw.githubusercontent.com/sugurumorimoto/dotfiles/0631b319c64505b99ba57cf3770771175834ac35/install.sh | bash
