name: Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: curl -sL https://raw.githubusercontent.com/sugurumorimoto/dotfiles/master/install.sh | sh
